services:
  vault-1:
    image: vault:1.13.1
    command: server
    cap_add:
      - IPC_LOCK
    volumes:
      - type: bind
        source: ./config
        target: /vault/config
      - type: volume
        source: vault_file
        target: /vault/file
    ports:
      - 8200:8200

volumes:
  vault_file:
